apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deployment
  labels:
    app: devapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devapp
  template:
    metadata:
      labels:
        app: devapp
    spec:
      containers:
      - name: nodeserver
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always